package com.project.sdk.mapper.food;

import com.project.sdk.dto.food.Food;
import com.project.sdk.dto.food.FoodType;

import java.util.List;

public interface FoodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zm_food
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zm_food
     *
     * @mbggenerated
     */
    int insert(Food record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zm_food
     *
     * @mbggenerated
     */
    int insertSelective(Food record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zm_food
     *
     * @mbggenerated
     */
    Food selectByPrimaryKey(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zm_food
     *
     * @mbggenerated
     */
    List<Food> queryList(Food record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zm_food
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Food record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zm_food
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Food record);

}