package com.project.sdk.export.dto.feedBack;

import java.util.Date;

public class FeedBackDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed_back.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed_back.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed_back.feed_back
     *
     * @mbggenerated
     */
    private String feedBack;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed_back.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed_back.id
     *
     * @return the value of feed_back.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed_back.id
     *
     * @param id the value for feed_back.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed_back.user_id
     *
     * @return the value of feed_back.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed_back.user_id
     *
     * @param userId the value for feed_back.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed_back.feed_back
     *
     * @return the value of feed_back.feed_back
     *
     * @mbggenerated
     */
    public String getFeedBack() {
        return feedBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed_back.feed_back
     *
     * @param feedBack the value for feed_back.feed_back
     *
     * @mbggenerated
     */
    public void setFeedBack(String feedBack) {
        this.feedBack = feedBack == null ? null : feedBack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed_back.create_time
     *
     * @return the value of feed_back.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed_back.create_time
     *
     * @param createTime the value for feed_back.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}