package com.project.sdk.export.dto.taskLog;

import java.util.Date;

public class TaskLogDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zm_task_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zm_task_log.task_id
     *
     * @mbggenerated
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zm_task_log.task_data
     *
     * @mbggenerated
     */
    private String taskData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zm_task_log.task_status
     *
     * @mbggenerated
     */
    private Integer taskStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zm_task_log.task_err_msg
     *
     * @mbggenerated
     */
    private String taskErrMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zm_task_log.creat_time
     *
     * @mbggenerated
     */
    private Date creatTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zm_task_log.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zm_task_log.creat_user
     *
     * @mbggenerated
     */
    private String creatUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zm_task_log.id
     *
     * @return the value of zm_task_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zm_task_log.id
     *
     * @param id the value for zm_task_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zm_task_log.task_id
     *
     * @return the value of zm_task_log.task_id
     *
     * @mbggenerated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zm_task_log.task_id
     *
     * @param taskId the value for zm_task_log.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zm_task_log.task_data
     *
     * @return the value of zm_task_log.task_data
     *
     * @mbggenerated
     */
    public String getTaskData() {
        return taskData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zm_task_log.task_data
     *
     * @param taskData the value for zm_task_log.task_data
     *
     * @mbggenerated
     */
    public void setTaskData(String taskData) {
        this.taskData = taskData == null ? null : taskData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zm_task_log.task_status
     *
     * @return the value of zm_task_log.task_status
     *
     * @mbggenerated
     */
    public Integer getTaskStatus() {
        return taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zm_task_log.task_status
     *
     * @param taskStatus the value for zm_task_log.task_status
     *
     * @mbggenerated
     */
    public void setTaskStatus(Integer taskStatus) {
        this.taskStatus = taskStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zm_task_log.task_err_msg
     *
     * @return the value of zm_task_log.task_err_msg
     *
     * @mbggenerated
     */
    public String getTaskErrMsg() {
        return taskErrMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zm_task_log.task_err_msg
     *
     * @param taskErrMsg the value for zm_task_log.task_err_msg
     *
     * @mbggenerated
     */
    public void setTaskErrMsg(String taskErrMsg) {
        this.taskErrMsg = taskErrMsg == null ? null : taskErrMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zm_task_log.creat_time
     *
     * @return the value of zm_task_log.creat_time
     *
     * @mbggenerated
     */
    public Date getCreatTime() {
        return creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zm_task_log.creat_time
     *
     * @param creatTime the value for zm_task_log.creat_time
     *
     * @mbggenerated
     */
    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zm_task_log.update_time
     *
     * @return the value of zm_task_log.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zm_task_log.update_time
     *
     * @param updateTime the value for zm_task_log.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zm_task_log.creat_user
     *
     * @return the value of zm_task_log.creat_user
     *
     * @mbggenerated
     */
    public String getCreatUser() {
        return creatUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zm_task_log.creat_user
     *
     * @param creatUser the value for zm_task_log.creat_user
     *
     * @mbggenerated
     */
    public void setCreatUser(String creatUser) {
        this.creatUser = creatUser == null ? null : creatUser.trim();
    }
}