package com.project.sdk.mapper.taskLog;

import com.project.sdk.dto.taskLog.TaskLog;

public interface TaskLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zm_task_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zm_task_log
     *
     * @mbggenerated
     */
    int insert(TaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zm_task_log
     *
     * @mbggenerated
     */
    int insertSelective(TaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zm_task_log
     *
     * @mbggenerated
     */
    TaskLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zm_task_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zm_task_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TaskLog record);
}