package com.project.sdk.export.dto.user;

import java.io.Serializable;
import java.util.Date;

public class UserExportDto implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zm_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zm_user.openID
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zm_user.phoneNum
     *
     * @mbggenerated
     */
    private Integer phonenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zm_user.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zm_user.sysType
     *
     * @mbggenerated
     */
    private Integer systype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zm_user.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zm_user.creatTime
     *
     * @mbggenerated
     */
    private Date creattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zm_user.updateTime
     *
     * @mbggenerated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zm_user.id
     *
     * @return the value of zm_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zm_user.id
     *
     * @param id the value for zm_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zm_user.openID
     *
     * @return the value of zm_user.openID
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zm_user.openID
     *
     * @param openid the value for zm_user.openID
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zm_user.phoneNum
     *
     * @return the value of zm_user.phoneNum
     *
     * @mbggenerated
     */
    public Integer getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zm_user.phoneNum
     *
     * @param phonenum the value for zm_user.phoneNum
     *
     * @mbggenerated
     */
    public void setPhonenum(Integer phonenum) {
        this.phonenum = phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zm_user.userName
     *
     * @return the value of zm_user.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zm_user.userName
     *
     * @param username the value for zm_user.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zm_user.sysType
     *
     * @return the value of zm_user.sysType
     *
     * @mbggenerated
     */
    public Integer getSystype() {
        return systype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zm_user.sysType
     *
     * @param systype the value for zm_user.sysType
     *
     * @mbggenerated
     */
    public void setSystype(Integer systype) {
        this.systype = systype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zm_user.code
     *
     * @return the value of zm_user.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zm_user.code
     *
     * @param code the value for zm_user.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zm_user.creatTime
     *
     * @return the value of zm_user.creatTime
     *
     * @mbggenerated
     */
    public Date getCreattime() {
        return creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zm_user.creatTime
     *
     * @param creattime the value for zm_user.creatTime
     *
     * @mbggenerated
     */
    public void setCreattime(Date creattime) {
        this.creattime = creattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zm_user.updateTime
     *
     * @return the value of zm_user.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zm_user.updateTime
     *
     * @param updatetime the value for zm_user.updateTime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}